[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
tui-input = { version = "*", features = ["ratatui-crossterm"]}
ratatui = { version = "0.30.0-alpha.2", features = [ "crossterm" ] }
color-eyre = "*"
